services:
  - type: web
    name: loan-application
    env: node
    rootDir: Loan Application
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port 10000 --strictPort
    autoDeploy: true

  - type: web
    name: loan-backend
    env: node
    rootDir: Backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
