services:
  - type: web
    name: loan-application
    env: static
    buildCommand: npm run build
    staticPublishPath: Loan Application/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
